language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
before_script:
  - npm run build
after_success:
  - npm run publish-coverage
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
